### ISSUE TITLE
Help with example install..  no errors seen

### ISSUE THREAD

**Issue by fils** [scienceai/jsonld-vis#5]
I am trying to get the example running.  I have the code copied to https://github.com/ESIPFed/provisium/tree/master/webapp/static/docs to play with.

where viztest.html is the starting HTML file.  

I got at error 
```  import declarations may only appear at top level of a module ```   
from Firefox Dev Edition 57

so I added type module like

```
<script src="./jsonldviz.js" type="module"></script>
```
to viztest.html.  

However:
1) I don't know what I am doing...
2) I get no errors now..  but no visual either...   

Is there some obvious miss I am just not seeing here...

**Comment by sballesteros** [comment]
Hello,

Not sure about the browser support for ES2015 modules and the `import` statement. I would recommend using a bundler like webpack or browserify to resolve the `import` statements.

**Comment by fils** [comment]
@sballesteros sorry for the delay..   other work...
I got this working.  I used npm to install d3 and d3-tip and using webpack.

```
  npm install d3
  npm install d3-tip
  webpack ./index.js bundle.js
```

However, for both Chrome (64) and Netscape dev edition  (57) I get paths that look to have a black fill.  See image.   

A CSS issue?

![screen shot 2017-11-06 at 3 24 54 am](https://user-images.githubusercontent.com/57170/32434060-a5c1f3ba-c2a2-11e7-9ea9-a1a144fdbeda.png)

**Comment by fils** [comment]
@sballesteros 

I think I got it.  Install ```npm install style-loader css-loader --save-dev```
and then following webpack.config.js works for me...

```js
const path = require('path');

 module.exports = {
     entry: ['./index.js','./index.css'],
     output: {
         path: path.resolve(__dirname, '.'),
         filename: 'bundle.js'
     },
     module: {
     loaders: [
         {
		test: /\.css$/,
		loaders: ["style-loader","css-loader"]
	 }
     ]
    },
 };
```

never used webpack before...   glad I know about it now!

**Comment by sballesteros** [comment]
cool glad you solved it!
